/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/authors`; params?: Router.UnknownInputParams; } | { pathname: `/awards`; params?: Router.UnknownInputParams; } | { pathname: `/beginner`; params?: Router.UnknownInputParams; } | { pathname: `/classics`; params?: Router.UnknownInputParams; } | { pathname: `/favorites`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/more`; params?: Router.UnknownInputParams; } | { pathname: `/movements`; params?: Router.UnknownInputParams; } | { pathname: `/paths`; params?: Router.UnknownInputParams; } | { pathname: `/reading-list`; params?: Router.UnknownInputParams; } | { pathname: `/search`; params?: Router.UnknownInputParams; } | { pathname: `/start`; params?: Router.UnknownInputParams; } | { pathname: `/works`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/author/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/award/[slug]`, params: Router.UnknownInputParams & { slug: string | number; } } | { pathname: `/movement/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/path/[slug]`, params: Router.UnknownInputParams & { slug: string | number; } } | { pathname: `/work/[slug]`, params: Router.UnknownInputParams & { slug: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/authors`; params?: Router.UnknownOutputParams; } | { pathname: `/awards`; params?: Router.UnknownOutputParams; } | { pathname: `/beginner`; params?: Router.UnknownOutputParams; } | { pathname: `/classics`; params?: Router.UnknownOutputParams; } | { pathname: `/favorites`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/more`; params?: Router.UnknownOutputParams; } | { pathname: `/movements`; params?: Router.UnknownOutputParams; } | { pathname: `/paths`; params?: Router.UnknownOutputParams; } | { pathname: `/reading-list`; params?: Router.UnknownOutputParams; } | { pathname: `/search`; params?: Router.UnknownOutputParams; } | { pathname: `/start`; params?: Router.UnknownOutputParams; } | { pathname: `/works`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/author/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/award/[slug]`, params: Router.UnknownOutputParams & { slug: string; } } | { pathname: `/movement/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/path/[slug]`, params: Router.UnknownOutputParams & { slug: string; } } | { pathname: `/work/[slug]`, params: Router.UnknownOutputParams & { slug: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/authors${`?${string}` | `#${string}` | ''}` | `/awards${`?${string}` | `#${string}` | ''}` | `/beginner${`?${string}` | `#${string}` | ''}` | `/classics${`?${string}` | `#${string}` | ''}` | `/favorites${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/more${`?${string}` | `#${string}` | ''}` | `/movements${`?${string}` | `#${string}` | ''}` | `/paths${`?${string}` | `#${string}` | ''}` | `/reading-list${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | `/start${`?${string}` | `#${string}` | ''}` | `/works${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/authors`; params?: Router.UnknownInputParams; } | { pathname: `/awards`; params?: Router.UnknownInputParams; } | { pathname: `/beginner`; params?: Router.UnknownInputParams; } | { pathname: `/classics`; params?: Router.UnknownInputParams; } | { pathname: `/favorites`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/more`; params?: Router.UnknownInputParams; } | { pathname: `/movements`; params?: Router.UnknownInputParams; } | { pathname: `/paths`; params?: Router.UnknownInputParams; } | { pathname: `/reading-list`; params?: Router.UnknownInputParams; } | { pathname: `/search`; params?: Router.UnknownInputParams; } | { pathname: `/start`; params?: Router.UnknownInputParams; } | { pathname: `/works`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | `/author/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/award/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/movement/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/path/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/work/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/author/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/award/[slug]`, params: Router.UnknownInputParams & { slug: string | number; } } | { pathname: `/movement/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/path/[slug]`, params: Router.UnknownInputParams & { slug: string | number; } } | { pathname: `/work/[slug]`, params: Router.UnknownInputParams & { slug: string | number; } };
    }
  }
}
