// Additional works data - append to add-missing-works.mjs newEntries array
// Copy these entries into the newEntries array in add-missing-works.mjs

{
  work: {
    id: "schindlers-ark", slug: "schindlers-ark",
    titleDisplayCn: "辛德勒的方舟", titleOriginal: "Schindler's Ark",
    authorName: "托马斯·肯尼利", countryOrRegion: "澳大利亚",
    firstPublishedYear: 1982,
    literaryCategory: "小说", literarySubcategory: "历史小说", workType: "长篇小说",
    difficultyLevel: 3, beginnerEntry: false, movementIds: ["realism"],
  },
  guide: {
    roleInPath: "CORE",
    suitability: "适合已有历史小说阅读经验的读者",
    oneSentencePositioning: "一个纳粹党员利用战争经济发家，又在最后一刻拯救了一千多名犹太人。",
    whyClassic: "1982年布克奖获奖作品，改编为电影《辛德勒的名单》。它是'非虚构小说'的代表作——基于真实人物，用小说手法组织叙事。",
    whyRead: "它提供了一个理解大屠杀的独特角度：不是从受害者视角，而是从一个 opportunist 德国商人的视角。故事的核心问题从开头就扣住读者——这个人什么时候会变？",
    suitableFor: "适合对二战历史有兴趣的读者。看过电影《辛德勒的名单》后再读小说会有更丰富的体验。",
    notSuitableFor: "对大屠杀题材敏感的读者需谨慎。",
    difficultyLevel: 3,
    difficultyReason: "叙事是传统线性结构，语言平实。篇幅约400页。历史背景本身沉重，但叙事方式不晦涩。人物众多，需要记住一些名字。",
    readingPrerequisites: "对二战和纳粹德国历史的基本了解有助于进入故事。",
    readingAdvice: "注意主角辛德勒的灰色地带——他不是传统意义上的'英雄'，这才是小说最有价值的地方。",
    beginnerEntry: false,
  },
},
{
  work: {
    id: "disgrace", slug: "disgrace",
    titleDisplayCn: "耻", titleOriginal: "Disgrace",
    authorName: "J.M.库切", countryOrRegion: "南非",
    firstPublishedYear: 1999,
    literaryCategory: "小说", literarySubcategory: "文学小说", workType: "长篇小说",
    difficultyLevel: 3, beginnerEntry: false, movementIds: ["realism", "postcolonial"],
  },
  guide: {
    roleInPath: "CORE",
    suitability: "适合已接触过严肃文学的读者",
    oneSentencePositioning: "一个南非白人教授在性丑闻后逃到乡下女儿农场，发现自己和女儿在后种族隔离时代的南非都成了边缘人。",
    whyClassic: "1999年布克奖获奖作品，库切两度获得布克奖。它在极克制的篇幅里讨论了后殖民时代的身份、暴力、赎罪和人与动物的关系。没有一句多余的话。",
    whyRead: "叙事冷静到近乎冷酷，但每一段都承载着重量。它不提供简单的道德判断——主角不是好人，但他的遭遇让人无法不同情。这种'道德复杂'的写作是库切的标志。",
    suitableFor: "适合喜欢心理深度、对后殖民议题有兴趣、欣赏精炼文笔的读者。篇幅短（约220页）。",
    notSuitableFor: "不适合期望'好人战胜困难'叙事的读者。性暴力场景有直接描写。",
    difficultyLevel: 3,
    difficultyReason: "篇幅短，语言精确不晦涩。但主题沉重（性暴力、种族冲突），道德立场暧昧不明，需要读者有独立思考的意愿。",
    readingPrerequisites: "对南非种族隔离历史的基本了解有帮助。",
    readingAdvice: "注意库切对动物的描写——小说中关于狗的线索不是副线，而是理解主题的关键。",
    beginnerEntry: false,
  },
},
{
  work: {
    id: "the-life-and-times-of-michael-k", slug: "michael-k",
    titleDisplayCn: "迈克尔·K的生活和时代", titleOriginal: "Life & Times of Michael K",
    authorName: "J.M.库切", countryOrRegion: "南非",
    firstPublishedYear: 1983,
    literaryCategory: "小说", literarySubcategory: "文学小说", workType: "长篇小说",
    difficultyLevel: 3, beginnerEntry: false, movementIds: ["realism", "postcolonial"],
  },
  guide: {
    roleInPath: "CORE",
    suitability: "适合已有文学阅读习惯的读者",
    oneSentencePositioning: "一个南非底层小人物在内战期间只想种南瓜，但社会不容许他独自安静地活着。",
    whyClassic: "1983年布克奖获奖作品。库切用极简的笔触写一个'不想参与历史'的人如何被历史碾压。它比《耻》更安静，但同样有力。",
    whyRead: "主角迈克尔·K是个简单的人——他只想种地。但他的简单愿望在一个撕裂的社会里变成了一种反抗。小说让人思考：一个人有没有权利退场？",
    suitableFor: "适合喜欢安静但有力量的小说的读者。对生存哲学有兴趣的人会特别喜欢。",
    notSuitableFor: "节奏缓慢，几乎没有对话或情节推进，不适合追求故事性的读者。",
    difficultyLevel: 3,
    difficultyReason: "篇幅短，语言简单。但叙事极简——大量留白和沉默需要读者自己填充意义。没有传统的情节推进。",
    readingPrerequisites: "不需要特殊知识。",
    readingAdvice: "接受它的慢。这不是一个关于'发生了什么'的故事，而是一个关于'存在'的故事。",
    beginnerEntry: false,
  },
},
{
  work: {
    id: "oscar-and-lucinda", slug: "oscar-and-lucinda",
    titleDisplayCn: "奥斯卡与露辛达", titleOriginal: "Oscar and Lucinda",
    authorName: "彼得·凯里", countryOrRegion: "澳大利亚",
    firstPublishedYear: 1988,
    literaryCategory: "小说", literarySubcategory: "文学小说", workType: "长篇小说",
    difficultyLevel: 3, beginnerEntry: false, movementIds: ["postmodernism"],
  },
  guide: {
    roleInPath: "CORE",
    suitability: "适合喜欢独特叙事风格的读者",
    oneSentencePositioning: "一个赌徒牧师和一个女玻璃商的跨洋爱情赌局。",
    whyClassic: "1988年布克奖获奖作品。彼得·凯里用19世纪澳洲殖民地为舞台，写了一个融合冒险、爱情、赌博和宗教讽刺的故事，叙事充满维多利亚小说的风味但又不失现代感。",
    whyRead: "角色极其鲜活——奥斯卡是一个患有赌瘾的圣公会牧师，这种矛盾本身就充满故事。叙事风格独特，像是狄更斯被昆汀·塔伦蒂诺改编过。",
    suitableFor: "适合喜欢独特叙事声音、对历史小说有兴趣的读者。对玻璃制作和赌博有感兴趣的会被额外吸引。",
    notSuitableFor: "叙事节奏有时松散，不适合期望紧凑情节的读者。",
    difficultyLevel: 3,
    difficultyReason: "语言风格模仿维多利亚小说，有特定的时代语调。叙事中有大量旁白和插话。情节线索较多。",
    readingPrerequisites: "不需要。对19世纪英国国教和澳洲殖民地历史的基本了解有帮助。",
    readingAdvice: "享受叙述者的声音——这个'讲故事的人'本身就是小说最大的魅力之一。",
    beginnerEntry: false,
  },
},
{
  work: {
    id: "true-history-of-the-kelly-gang", slug: "true-history-of-the-kelly-gang",
    titleDisplayCn: "凯利帮真史", titleOriginal: "True History of the Kelly Gang",
    authorName: "彼得·凯里", countryOrRegion: "澳大利亚",
    firstPublishedYear: 2001,
    literaryCategory: "小说", literarySubcategory: "历史小说", workType: "长篇小说",
    difficultyLevel: 3, beginnerEntry: false, movementIds: ["postmodernism"],
  },
  guide: {
    roleInPath: "CORE",
    suitability: "适合对澳大利亚文学有兴趣的读者",
    oneSentencePositioning: "澳洲传奇绿林好汉凯利帮的'自述'——用他本人的口语写成。",
    whyClassic: "2001年布克奖获奖作品，凯里第二次获奖。他用一种令人震撼的'不标准英语'写了一个强盗的告白，既是一部历史冒险小说，也是对殖民叙事的颠覆。",
    whyRead: "叙事语言是最大的亮点——凯利帮的口语充满语法错误、拼写变异，但这种'不标准'恰恰传递了人物的真实声音。读起来像是一份压在箱底多年的手稿。",
    suitableFor: "适合对澳洲历史有兴趣的读者。对'民间英雄'叙事和西部（其实是澳洲）冒险有兴趣的人。",
    notSuitableFor: "非标准叙事语言可能让部分读者不适应。暴力场景有直接描写。",
    difficultyLevel: 3,
    difficultyReason: "叙事语言故意不标准（拼写、语法变异），需要读者适应。但故事本身是冒险叙事，情节推进快。",
    readingPrerequisites: "对澳洲殖民历史（流放犯制度）的基本了解有帮助。",
    readingAdvice: "不要被非标准拼写吓退——把这当成凯利本人在对你说话。读到第三页就会习惯。",
    beginnerEntry: false,
  },
},
{
  work: {
    id: "the-god-of-small-things", slug: "the-god-of-small-things",
    titleDisplayCn: "微物之神", titleOriginal: "The God of Small Things",
    authorName: "阿兰达蒂·洛伊", countryOrRegion: "印度",
    firstPublishedYear: 1997,
    literaryCategory: "小说", literarySubcategory: "文学小说", workType: "长篇小说",
    difficultyLevel: 4, beginnerEntry: false, movementIds: ["postmodernism", "postcolonial"],
  },
  guide: {
    roleInPath: "ADVANCED",
    suitability: "适合已有丰富文学阅读经验的读者",
    oneSentencePositioning: "一对印度双胞胎的童年如何被种姓制度和家族秘密摧毁。",
    whyClassic: "1997年布克奖获奖作品，洛伊的第一部小说，也是她迄今唯一的长篇小说。它以极诗意的语言和碎片化叙事，展示了种姓制度如何渗透到最亲密的家庭关系中。",
    whyRead: "语言密度极高，每一页都有可以停下来品味的地方。它不是线形讲故事，而是像剥洋葱一层层揭开一个夏天的悲剧。洛伊的语言是感官性的——你能闻到、听到、触摸到那个闷热的印度南方小镇。",
    suitableFor: "适合喜欢精致语言和复杂叙事的读者。对印度社会、种姓制度有兴趣的人会获得很深的体验。",
    notSuitableFor: "不适合初学者。碎片化叙事、时间跳跃、大量文化特定细节对读者要求较高。",
    difficultyLevel: 4,
    difficultyReason: "非线形叙事，时间在1993年和1969年之间跳跃。语言诗性、密度高。包含大量印度南方的文化、饮食、宗教细节。需要读者集中注意力。",
    readingPrerequisites: "建议有至少读过10部以上严肃文学作品的阅读经验。对印度种姓制度的基本了解有帮助。",
    readingAdvice: "第一次读时不要强求理清所有时间线。让语言带你走。有必要的话列一个人物关系表。",
    beginnerEntry: false,
  },
},
{
  work: {
    id: "the-white-tiger", slug: "the-white-tiger",
    titleDisplayCn: "白老虎", titleOriginal: "The White Tiger",
    authorName: "阿拉文德·阿迪加", countryOrRegion: "印度",
    firstPublishedYear: 2008,
    literaryCategory: "小说", literarySubcategory: "文学小说", workType: "长篇小说",
    difficultyLevel: 2, beginnerEntry: true, movementIds: ["realism", "postcolonial"],
  },
  guide: {
    roleInPath: "ENTRY",
    suitability: "适合作为后殖民小说入门",
    oneSentencePositioning: "一个印度穷小子用七晚给中国总理写信，讲述自己如何从一个底层司机变成成功企业家——以及他为此杀了谁。",
    whyClassic: "2008年布克奖获奖作品。它以黑色幽默的方式揭示了现代印度的另一面：不是软件园和外包中心，而是黑暗、腐败、种姓压迫的另一面。",
    whyRead: "像一个犯罪故事一样吸引人——主角在信里说'I killed a man'，然后倒叙告诉你为什么。叙事节奏快，语言辛辣幽默。读者会在笑过之后发现自己被带入了不道德的立场。",
    suitableFor: "适合喜欢黑色幽默和社会讽刺的读者。想了解当代印度社会另一面的读者会收获丰富。",
    notSuitableFor: "对道德立场黑白分明的读者可能不适——主角是个杀人犯叙述者，你会发现自己忍不住同情他。",
    difficultyLevel: 2,
    difficultyReason: "叙事是线性倒叙，语言直接有力，充满口语化表达。故事性强，悬念驱动。社会批判深刻但不影响阅读流畅性。",
    readingPrerequisites: "不需要。对印度种姓制度和当代社会经济差距的基本了解有助于理解背景。",
    readingAdvice: "主角巴尔拉姆是一个'不可靠叙述者'——相信他说的每一句话，也要怀疑他说的每一句话。",
    beginnerEntry: true,
  },
},
{
  work: {
    id: "a-visit-from-the-goon-squad", slug: "goon-squad",
    titleDisplayCn: "恶棍来访", titleOriginal: "A Visit from the Goon Squad",
    authorName: "珍妮弗·伊根", countryOrRegion: "美国",
    firstPublishedYear: 2010,
    literaryCategory: "小说", literarySubcategory: "实验小说", workType: "长篇小说",
    difficultyLevel: 3, beginnerEntry: false, movementIds: ["postmodernism"],
  },
  guide: {
    roleInPath: "CORE",
    suitability: "适合对实验性叙事有兴趣的读者",
    oneSentencePositioning: "一本由13个相互关联的短篇组成的小说，跨越40年，人物在不同篇章中以主配角身份轮转。",
    whyClassic: "2011年普利策小说奖获奖作品。它以碎片化的短篇结构写成，章节之间时间跳跃、叙述视角变换、甚至有一章完全用PPT格式展示。它对'小说还能怎么讲'做出了激进但成功的实验。",
    whyRead: "每一章都可以当作独立的短篇来读，但连起来会拼出一幅更大的图景。它关于时间如何改变人——每个角色年轻时都以为自己是主角，最终发现只是群演。",
    suitableFor: "适合喜欢实验性叙事、对音乐行业文化有兴趣的读者。适合碎片化阅读（每章独立）。",
    notSuitableFor: "不适合期望传统线形叙事的读者。人物众多，需要记住大量的名字和关系。",
    difficultyLevel: 3,
    difficultyReason: "结构是主要门槛——13个章节是独立短篇，时间跳跃，需要读者自己拼凑完整叙事。但每一章本身的叙事是清晰流畅的。",
    readingPrerequisites: "不需要。对朋克摇滚文化有一些了解会增添阅读乐趣。",
    readingAdvice: "一章一章地读，不需要强求记住所有人。读到后面会不断有'啊原来是他'的惊喜时刻。",
    beginnerEntry: false,
  },
},
{
  work: {
    id: "the-road", slug: "the-road",
    titleDisplayCn: "长路", titleOriginal: "The Road",
    authorName: "科马克·麦卡锡", countryOrRegion: "美国",
    firstPublishedYear: 2006,
    literaryCategory: "小说", literarySubcategory: "末世小说", workType: "长篇小说",
    difficultyLevel: 3, beginnerEntry: false, movementIds: [],
  },
  guide: {
    roleInPath: "CORE",
    suitability: "适合已建立阅读习惯的读者",
    oneSentencePositioning: "末日之后，一对父子在灰烬覆盖的美国大地上向南跋涉。",
    whyClassic: "2007年普利策小说奖获奖作品。麦卡锡用极为节制的语言（没有引号、没有章节名、几乎没有修饰语）写了一个末日寓言。它被广泛认为是21世纪最重要的美国小说之一。",
    whyRead: "极简的语言制造了一种'灰烬感'——你读的时候会感到寒冷、饥饿和绝望。但它又是一部关于父爱的故事。在'世界彻底失败'的设定下，父亲对孩子的责任变得极其纯粹和震撼。",
    suitableFor: "适合喜欢沉重、严肃题材的读者。对末日设定有兴趣的人。",
    notSuitableFor: "格调整体灰暗绝望，不适合情绪低落时阅读。生存困境描写具体，部分场景严峻。",
    difficultyLevel: 3,
    difficultyReason: "语言本身不复杂——甚至可以说简单。但麦卡锡独特的标点风格（无引号、无章节分割）需要适应。情感强度非常高，阅读体验沉重。篇幅适中（约280页）。",
    readingPrerequisites: "不需要。",
    readingAdvice: "注意麦卡锡的标点用法——他不使用引号，对话和叙述混在一起。这种'没有边界'的写作风格本身就是小说世界观的一部分。",
    beginnerEntry: false,
  },
},
